Pose
Team3256/Offseason_Bot_2024 pull request #20
Opened 2024-07-13 22:27 UTC by chaoticthegreat

Closes RCD-18

2024-07-14 00:15 UTC, realjoshuau requested changes
shouldn't `updateVision` be called during a periodic?

2024-07-14 15:36 UTC, chaoticthegreat commented
> shouldn't `updateVision` be called during a periodic?

It is ?

2024-07-15 03:28 UTC, realjoshuau commented
My bad, the diff showed it weirdly. Looks good (maybe some checks if the LL disconnects?)

2024-07-15 03:28 UTC, realjoshuau approved these changes

2024-07-15 04:07 UTC, merged